cd ..

python construct_ensemble.py \
	--name test_model_cover \
	--only_train_nonexisting True \
	--slurm False \
	--slurm_partition gpu \
	--pt_dataset_name example_ds \
	--community_dataset_name InsectArmageddon_test \
	--c_learning_rate 5e-05 \
	--c_weight_decay 1e-05 \
	--c_n_epochs -1 \
	--c_batch_size 4 \
	--c_image_size 448 \
	--c_use_occlusion_augmentation False \
	--c_threshold 0.2 \
	--c_normalization torch \
	--c_enriched_wsol_output True \
	--c_loss cce \
	--cm_pooling_method lse \
	--wf_base_network efficientnet_v2_l \
	--wf_fpn_spec P2-512 \
	--s_learning_rate 1e-05 \
	--s_weight_decay 1e-05 \
	--s_n_epochs -1 \
	--s_batch_size 4 \
	--s_image_size 448 \
	--s_normalization torch \
	--s_use_cutout True \
	--s_ic_min 32 \
	--s_ic_max 224 \
	--s_ic_reps 2 \
	--s_image_caching True \
	--s_max_workers 16 \
	--s_loss bce_dice \
	--sf_base_network efficientnet_v2_l \
	--sf_fpn_spec P2-512 \
	--cp_learning_rate 1e-05 1e-05 \
	--cp_n_epochs 30 \
	--cp_weight_decay 0 \
	--cp_dataset_mode weekly \
	--cp_pheno_model fs \
	--cp_image_size 1536 2688 \
	--cp_loss hell \
	--cp_pheno_loss mae \
	--cp_normalization torch \
	--cp_mc_params padded,896,2 \
	--cp_aug_strat hflip,vflip,rot90 \
	--cp_batch_size 1 \
	--cp_max_workers 16 \
	--cpm_cover_head_type default \
	--cpm_pheno_model fs \
	--use_ensemble True \
	--ensemble_epochs 20 30 10 \
	--ensemble_models efficientnet_v2_l \
	--n_ensemble_reps 2 \
	--zeroshot False